#--------------------------------------------------------------------------------------
# Database section
#--------------------------------------------------------------------------------------
[database]

[database.influxdb]
bucket = ""
org = ""
url = "0.0.0.0:8086"
time_out = "30_000"

#--------------------------------------------------------------------------------------
# Motor section
#--------------------------------------------------------------------------------------

[motor]

m_type = ["elevation", "azimuth"]

[motor.elevation]
stp = 1
dir = 2
ena = 3
eng_1 = 1
eng_2 = 2
end_stop = 10
step = 20_000

[motor.azimuth]
stp = 20
dir = 16
ena = 21
eng_1 = 80
eng_2 = 310
end_stop = 12
step = 20_000